### ISSUE TITLE
Failed to process voice-pack

### ISSUE THREAD

**Issue by MarioBinder** [lbormann/autodarts-caller#4]
I get for some voice-packs an exception:

`.\autodarts-caller.exe -U "myemail.de" -P "mypassword" -B "my boardid" -M "D:/Apps/autodarts-caller" -C charles-m-english-us-canada`

```
##########################################
       WELCOME TO AUTODARTS-CALLER
##########################################
VERSION: 2.6.0
RUNNING OS: Windows | nt | 10
SUPPORTED GAME-VARIANTS: X01 Cricket Random Checkout


Failed to process voice-pack: en-US-Wavenet-H-FEMALE-v3

Failed to process voice-pack: en-US-Wavenet-I-MALE-v3

Failed to process voice-pack: en-US-Wavenet-J-MALE-v3

Failed to process voice-pack: en-US-Wavenet-F-FEMALE-v3

Failed to process voice-pack: en-US-Stephen-Male-v3

Failed to process voice-pack: en-US-Ivy-Female-v3

Failed to process voice-pack: en-US-Kendra-Female-v3

Failed to process voice-pack: en-US-Joey-Male-v3

Failed to process voice-pack: en-US-Joanna-Female-v3

15 voice-pack(s) found.
aiden-m-english-uk
alicia-f-english-us-canada
ava-f-english-us-canada
charles-m-english-us-canada
clint-m-english-us-canada
emily-f-english-scottish
en-us-wavenet-a-male-v3
en-us-wavenet-e-female-v3
en-us-wavenet-g-female-v3
ethan-m-english-us-canada
kushal-m-english-india
kylie-f-english-australia
mitch-m-english-australia
ruby-f-english-uk
theo-m-english-uk

Your current caller: charles-m-english-us-canada knows 735 Sound-file-key(s)

Receive token failed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "autodarts-caller.py", line 1684, in process
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by MarioBinder** [comment]
it works now after trying to execute a several times
